package pl.siedlar.zipinstaller;

import android.app.*;import android.content.*;import android.content.pm.PackageInstaller;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.provider.Settings;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.zip.*;

public class MainActivity extends Activity {
 static final int PICK=7; TextView state,info; Button open; Uri pending; boolean busy;
 public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());incoming(getIntent());}
 public void onNewIntent(Intent i){super.onNewIntent(i);incoming(i);}
 public void onResume(){super.onResume();if(pending!=null&&Build.VERSION.SDK_INT>=26&&getPackageManager().canRequestPackageInstalls()){Uri u=pending;pending=null;process(u);}}
 View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER_HORIZONTAL);r.setPadding(dp(20),dp(28),dp(20),dp(24));r.setBackgroundColor(Color.parseColor("#101512")); TextView logo=t("ZIP↓",26,"#101512",true);logo.setGravity(Gravity.CENTER);logo.setBackground(bg("#F27C68",24));r.addView(logo,new LinearLayout.LayoutParams(dp(78),dp(78))); TextView h=t("ZIP Pilot",30,"#F4EEE4",true);h.setGravity(17);lp(r,h,0,18);TextView sub=t("Otwiera paczkę i robi właściwą rzecz za Ciebie",14,"#A8B2AC",false);sub.setGravity(17);lp(r,sub,0,22); LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(18),dp(18),dp(18),dp(18));card.setBackground(bg("#18201C",22));state=t("Gotowy",21,"#F4EEE4",true);info=t("APK → instalacja\nXAPK / APKS / ZIP z APK → instalacja paczki\nZwykły ZIP → wypakowanie do Downloads",13,"#A8B2AC",false);card.addView(state);lp(card,info,8,0);lp(r,card,0,14);open=new Button(this);open.setText("OTWÓRZ PACZKĘ");open.setTextColor(Color.parseColor("#101512"));open.setTypeface(null,1);open.setBackground(bg("#F4EEE4",18));open.setOnClickListener(v->pick());r.addView(open,new LinearLayout.LayoutParams(-1,dp(58)));TextView n=t("Android może poprosić o jedno systemowe potwierdzenie instalacji. Aplikacja nie uruchamia skryptów z ZIP-a.",11,"#74817A",false);n.setGravity(17);lp(r,n,18,0);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);return s;}
 TextView t(String x,int sz,String c,boolean b){TextView v=new TextView(this);v.setText(x);v.setTextSize(sz);v.setTextColor(Color.parseColor(c));if(b)v.setTypeface(null,1);return v;} void lp(LinearLayout p,View v,int top,int bottom){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(-1,-2);x.topMargin=dp(top);x.bottomMargin=dp(bottom);p.addView(v,x);} GradientDrawable bg(String c,int rad){GradientDrawable g=new GradientDrawable();g.setColor(Color.parseColor(c));g.setCornerRadius(dp(rad));return g;} int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK);} protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null&&d.getData()!=null)process(d.getData());}
 void incoming(Intent i){if(i==null)return;Uri u=null;if(Intent.ACTION_VIEW.equals(i.getAction()))u=i.getData();if(Intent.ACTION_SEND.equals(i.getAction())){if(Build.VERSION.SDK_INT>=33)u=i.getParcelableExtra(Intent.EXTRA_STREAM,Uri.class);else{u=i.getParcelableExtra(Intent.EXTRA_STREAM);}}if(u!=null)process(u);}
 void process(Uri u){if(busy)return;busy=true;set("Sprawdzam paczkę…","Rozpoznaję zawartość i wybieram akcję.");new Thread(()->{try{String name=name(u),lo=name.toLowerCase(Locale.ROOT);if(lo.endsWith(".apk")){File f=copyCache(u,"base.apk");runOnUiThread(()->permissionOrInstall(u,Collections.singletonList(f)));return;}if(lo.endsWith(".zip")||lo.endsWith(".xapk")||lo.endsWith(".apks")||lo.endsWith(".apkm")){File z=copyCache(u,"in.zip");List<File>a=apks(z);if(!a.isEmpty()){runOnUiThread(()->permissionOrInstall(u,a));return;}int n=unzipDownloads(z,base(name));runOnUiThread(()->done("Wypakowane",n+" plików → Downloads/ZIP Pilot/"+base(name)));return;}runOnUiThread(()->done("Nie znam formatu","Obsługuję APK, ZIP, XAPK, APKS i APKM."));}catch(Exception e){runOnUiThread(()->done("Błąd paczki",String.valueOf(e.getMessage())));}}).start();}
 void permissionOrInstall(Uri original,List<File> files){if(Build.VERSION.SDK_INT>=26&&!getPackageManager().canRequestPackageInstalls()){pending=original;busy=false;set("Potrzebna jedna zgoda Androida","Włącz „Zezwalaj z tego źródła”, potem wróć tutaj.");startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+getPackageName())));return;}set("Instaluję…",files.size()+" plik(ów) APK");new Thread(()->{try{install(files);runOnUiThread(()->done("Przekazane do Androida","Potwierdź instalację, jeśli system o to poprosi."));}catch(Exception e){runOnUiThread(()->done("Błąd instalacji",String.valueOf(e.getMessage())));}}).start();}
 void install(List<File> fs)throws Exception{PackageInstaller pi=getPackageManager().getPackageInstaller();int id=pi.createSession(new PackageInstaller.SessionParams(PackageInstaller.SessionParams.MODE_FULL_INSTALL));PackageInstaller.Session s=pi.openSession(id);try{for(int i=0;i<fs.size();i++){File f=fs.get(i);try(InputStream in=new FileInputStream(f);OutputStream out=s.openWrite(i==0?"base.apk":"split"+i+".apk",0,f.length())){cp(in,out);s.fsync(out);}}Intent ri=new Intent(this,InstallResultReceiver.class);PendingIntent p=PendingIntent.getBroadcast(this,id,ri,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_MUTABLE);s.commit(p.getIntentSender());}finally{s.close();}}
 List<File> apks(File z)throws Exception{List<File>o=new ArrayList<>();File d=new File(getCacheDir(),"splits"+System.nanoTime());d.mkdirs();try(ZipInputStream in=new ZipInputStream(new FileInputStream(z))){ZipEntry e;while((e=in.getNextEntry())!=null){if(e.isDirectory()||!e.getName().toLowerCase(Locale.ROOT).endsWith(".apk"))continue;File f=new File(d,safe(new File(e.getName()).getName()));try(OutputStream x=new FileOutputStream(f)){cp(in,x);}o.add(f);}}o.sort((a,b)->a.getName().equalsIgnoreCase("base.apk")?-1:b.getName().equalsIgnoreCase("base.apk")?1:a.getName().compareTo(b.getName()));return o;}
 int unzipDownloads(File z,String folder)throws Exception{int n=0;try(ZipInputStream in=new ZipInputStream(new FileInputStream(z))){ZipEntry e;while((e=in.getNextEntry())!=null){if(e.isDirectory())continue;String q=e.getName().replace('\\','/');if(q.startsWith("/")||q.contains("../"))throw new IOException("Niebezpieczna ścieżka ZIP");if(Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,new File(q).getName());v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/ZIP Pilot/"+safe(folder)+"/");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);try(OutputStream out=getContentResolver().openOutputStream(u)){cp(in,out);}}else{File root=new File(getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS),"ZIP Pilot/"+safe(folder));root.mkdirs();File f=new File(root,safe(new File(q).getName()));try(OutputStream out=new FileOutputStream(f)){cp(in,out);}}n++;}}return n;}
 File copyCache(Uri u,String n)throws Exception{File f=new File(getCacheDir(),n);try(InputStream in=getContentResolver().openInputStream(u);OutputStream out=new FileOutputStream(f)){if(in==null)throw new IOException("Brak dostępu do pliku");cp(in,out);}return f;} void cp(InputStream i,OutputStream o)throws IOException{byte[]b=new byte[65536];int n;while((n=i.read(b))>0)o.write(b,0,n);o.flush();}
 String name(Uri u){String r=null;try(android.database.Cursor c=getContentResolver().query(u,new String[]{android.provider.OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())r=c.getString(0);}catch(Exception ignored){}return r==null?(u.getLastPathSegment()==null?"paczka":u.getLastPathSegment()):r;} String safe(String s){return s.replaceAll("[^a-zA-Z0-9._() -]","_");} String base(String s){int i=s.lastIndexOf('.');return i>0?s.substring(0,i):s;} void done(String a,String b){busy=false;open.setEnabled(true);set(a,b);} void set(String a,String b){state.setText(a);info.setText(b);}
}
