name: Casino container validation
on:
  pull_request:
    branches: [main]
jobs:
  portal:
    if: github.head_ref == 'casino-ci-validation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Portal container
        run: docker build --progress=plain -f casino/deploy/Dockerfile.portal.vercel -t casino-portal:test casino
